sonar.projectKey=EduardoMsf_for-fun-nest
sonar.organization=eduardomsf

# Source code
sonar.sources=src

# Tests
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

# Exclusions
sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
